version: '3.3'
services:
    zinclabs:
        image: 'public.ecr.aws/zinclabs/zinc:${SOFTWARE_VERSION_TAG}'
        restart: always
        volumes:
            - './data:/data'
        environment:
            - ZINC_DATA_PATH=/data
            - ZINC_FIRST_ADMIN_USER=${ADMIN_EMAIL}
            - 'ZINC_FIRST_ADMIN_PASSWORD=${ADMIN_PASSWORD}'
        ports:
            - '172.17.0.1:4080:4080'
